# Generated by Django 4.0.5 on 2022-06-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_photo_file_alter_photo_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
